name: publish-image

on:
  push:
    tags:
      - "*"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      -
        name: Extract meta
        id: meta
        run: |
          TAG="${GITHUB_REF#refs/tags/}"
          NODE_VERSION=$(echo "$TAG" | sed -nE 's/.*node-([0-9.]+).*/\1/p')
          echo "image_tag=$TAG" >> $GITHUB_OUTPUT
          echo "node_version=$NODE_VERSION" >> $GITHUB_OUTPUT
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          build-args: |
            NODE_VERSION=${{ steps.meta.outputs.node_version }}
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ghcr.io/cubic-lab/node-chromium:${{ steps.meta.outputs.image_tag }}